/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.tfedorov.gradledependencies.sciencelibrary

import com.tfedorov.gradledependencies.booktransitive.Book
import org.slf4j.LoggerFactory

object ScienceLibrary {

  private val logger = LoggerFactory.getLogger(this.getClass)

  def takeFromLibrary: String = {
    logger.info("Fetching library name")
    "I take from the 'Science Library'  " + Book.book
  }
}
